### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by Kfzz1** [brant-ruan/metarget#32]
![image](https://user-images.githubusercontent.com/52166110/118225473-ce69ff00-b4b7-11eb-9bdd-c81696115504.png)

**Comment by Kfzz1** [comment]
There is an error: pod has unbound immediate PersistentVolumeClaims
![image](https://user-images.githubusercontent.com/52166110/118225745-420c0c00-b4b8-11eb-93bd-5f8bcc32cbec.png)

**Comment by brant-ruan** [comment]
Thanks, `kompose` failed to convert volumes correctly. We are working to add `hostPath` volumes.
